# 판다스 데이터 분석

In [4]:
# import
import numpy as np  
import pandas as pd

In [5]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [6]:
x = np.array([9904312, 3448737, 2890451, 2466052])
x

array([9904312, 3448737, 2890451, 2466052])

In [7]:
pd.Series(range(10,14))

0    10
1    11
2    12
3    13
dtype: int64

In [8]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [9]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [10]:
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

### 시리즈 연산

In [11]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

### 시리즈 인덱싱

In [12]:
s[1],s["부산"]

(3448737, 3448737)

In [13]:
s[[0, 3, 1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [14]:
s[["서울", "대구", "부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [16]:
s[(250e4 < s) & (s < 500e4)]  # e4 = 0000

Series([], Name: 인구, dtype: int64)

In [22]:
# 시리즈 슬라이싱
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [23]:
s["부산":"대구"]  #인덱스네임으로 부르면 이름까지 포함(이게 더 편할 듯?)

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [24]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [29]:
s0.a, s.부산

(0, 3448737)

### 시리즈와 딕셔너리 자료형

In [30]:
"서울" in s

True

In [32]:
"대전" in s

False

In [37]:
for k, v in s.items():
    print(f"{k} = {v}")

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [38]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [40]:
# 딕셔너리는 순서를 보장이 안되어서 순서를 정하려면 인덱스 리스트로 지정
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [41]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [42]:
ds = s - s2 

In [43]:
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [44]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [45]:
ds.notnull

<bound method Series.notnull of 대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64>

In [46]:
#조건식 안에 메소드도 가능
rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

In [47]:
# 데이터 갱신
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [48]:
# 데이터 추가도 가능
rs["대구"] = 1.41
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [49]:
del rs["서울"]
rs

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64

In [56]:
ab = pd.Series([555,444,333,222],index=range(1,5))
ab

1    555
2    444
3    333
4    222
dtype: int64

In [58]:
bc = pd.Series([888,777,666,333],index=range(2,6))
bc

2    888
3    777
4    666
5    333
dtype: int64

In [59]:
nb = bc - ab
nb

1      NaN
2    444.0
3    444.0
4    444.0
5      NaN
dtype: float64

In [61]:
nb = bc * ab
nb

1         NaN
2    394272.0
3    258741.0
4    147852.0
5         NaN
dtype: float64

In [63]:
nb = bc.values + ab.values
nb

array([1443, 1221,  999,  555], dtype=int64)

### 데이터프레임 클래스

In [69]:
data = {
    "2015" : [9904312, 3448737, 2890451, 2466052],
    "2010" : [9631482, 3393191, 2632035, 2431774],
    "2005" : [9762546, 3512547, 2517680, 2456016],
    "2000" : [9853972, 3655437, 2466338, 2473990],
    "지역" : ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율" : [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [70]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [71]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [72]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [73]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [75]:
dataA = {
    "가" : [12, "ㅋ", -43, 50, 55],
    "나" : [44, "ㄷ", -55, 88, 72],
    "다" : [88, "ㄹ", -92, 200, 12],
    "라" : [21, "ㅂ", -98, 12, 43],
    "마" : [55, "ㅅ", -77, 53, 77]
}
columnsA = ["가","나","다","라","마"]
indexA = ["나이","이름","위치","목표","현재수준"]
dfA = pd.DataFrame(dataA, index=indexA, columns=columnsA)
dfA

가    나    다    라    마
나이     12   44   88   21   55
이름      ㅋ    ㄷ    ㄹ    ㅂ    ㅅ
위치    -43  -55  -92  -98  -77
목표     50   88  200   12   53
현재수준   55   72   12   43   77

In [76]:
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [77]:
# 열 갱신 
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [78]:
# 열 추가 
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시                                                                       
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [79]:
# 열 삭제
del df["2010-2015 증가율"]
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [93]:
# 하나만 부르면 시리즈
df.지역,df["지역"]

(도시
 서울    수도권
 부산    경상권
 인천    수도권
 대구    경상권
 Name: 지역, dtype: object,
 도시
 서울    수도권
 부산    경상권
 인천    수도권
 대구    경상권
 Name: 지역, dtype: object)

In [97]:
# 여러개 열을 부르면 데이터 프레임
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [101]:
df[["2010"]]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [104]:
df[0]

KeyError: 0

In [102]:
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [105]:
df2[:]

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

### 행 인덱싱

In [108]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [114]:
df[:'서울']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [121]:
df[1:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           -3.4

In [122]:
df["서울":"부산"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [124]:
df[0:3]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

### 개별 데이터 인덱싱

In [126]:
#[열][행]
df['2015']["서울"]

9904312

### 연습문제 4.1.3

In [129]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [131]:
# 1번 모든 학생의 수학 점수를 시리즈로 나타낸다.
df["수학"]

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [133]:
# 2번 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
df[["수학","영어"]]

수학  영어
춘향  90  90
몽룡  60  70
향단  80  60
방자  70  40

In [139]:
# 3번 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df["평균 점수"] = ((df["국어"]+df["영어"]+df["수학"])/3).round(2)
df

국어  영어  수학  평균 점수
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [143]:
# 4번 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.
df["영어"]["방자"] = 80
df["평균 점수"] = ((df["국어"]+df["영어"]+df["수학"])/3).round(2)
df

국어  영어  수학  평균 점수
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  60.00

In [159]:
# 5번 춘향의 점수를 데이터프레임으로 나타낸다.
df[:'춘향'].T

춘향
국어     80.00
영어     90.00
수학     90.00
평균 점수  86.67

In [160]:
# 6번 향단의 점수를 시리즈로 나타낸다
# 행열 바꾸고 표현
df.T['향단']

국어       70.0
영어       60.0
수학       80.0
평균 점수    70.0
Name: 향단, dtype: float64