# Numpy

### Numpy Array

In [28]:
# 리스트와 넘파이와 어레이 속도 비교
import numpy as np  
np_arr = np.arange(1000000)
nu_list = [i for i in range(100000)]

In [2]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 148 ms


In [3]:
%%time
for i in range(100):
   np.sum(np_arr)

Wall time: 47 ms


### 1차원 배열 만들기

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(ar)

numpy.ndarray

In [7]:
ar.shape

(10,)

### 백터화 연산

In [12]:
# 일반적인 리스트 표현식
al = [2 * i  for i in range(1,11)]
al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [13]:
al*2

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [10]:
# numpy 표현식
2 * ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [19]:
2 * a + b

array([12, 24, 36])

In [20]:
a == 2

array([False,  True, False])

In [21]:
b > 15

array([False,  True,  True])

In [22]:
(a == 2) & (b > 10)

array([False,  True, False])

In [23]:
c = np.array([[0, 1, 2], [3, 4, 5]]) 
c

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
c.shape

(2, 3)

In [26]:
len(c),len(c[0])

(2, 3)

In [35]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [34]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [37]:
# 배열의 크기
d.shape

(2, 3, 4)

In [39]:
# 차원의 갯수
d.ndim

3

In [51]:
a = np.array([0, 1, 2, 3, 4])

In [52]:
a[2],a[-1]

(2, 4)

In [56]:
a[0, 1]

1

In [54]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [55]:
a[:,1:3]

array([[1, 2],
       [5, 6]])

In [61]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [62]:
m[1,2]

7

In [63]:
m[2,4]

14

In [130]:
#[7,12] 만들기
m[1:,2]

array([ 7, 12])

In [132]:
# [[3,4],[8,9]] 만들기 
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [95]:
m[3:,:2]

array([], shape=(0, 2), dtype=int32)

### 배열 인덱싱 

In [98]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [99]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [100]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [101]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [102]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [103]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [106]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [121]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [122]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [123]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [133]:
x[x % 3 == 0 , x % 4 == 1]

IndexError: too many indices for array