# 배열의 생성과 변형

In [3]:
import numpy as np  

In [4]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [5]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [6]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [8]:
x = np.array([1, 2, 3], dtype='float32')
x.dtype

dtype('float32')

In [9]:
### Inf와 NaN
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [10]:
np.log(0)

-inf

In [11]:
np.exp(-np.inf)

0.0

In [12]:
### 배열생성

In [14]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [15]:
a.dtype

dtype('float64')

In [16]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
c = np.zeros((5, 2), dtype="int")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [20]:
c.dtype

dtype('int32')

In [23]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [24]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [25]:
z = np.zeros_like(f, dtype="f")


array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [28]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [48]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

###  전치 연산

In [49]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [52]:
A @ A.T

array([[14, 32],
       [32, 77]])

#### 배열의 크기 변형

In [53]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a.reshape(3,2,-1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [60]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [66]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [67]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [68]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [69]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [73]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [74]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [95]:
d = np.hstack([a,b])
d

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [100]:
c = np.arange(10,151,10)
c

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [97]:
f = c.reshape(3,5)
f

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [98]:
np.vstack([d,f,d,f])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

#### 2차원 그리드 포인트 생성

In [101]:
x = np.arange(3)
x

array([0, 1, 2])

In [102]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [103]:
X, Y = np.meshgrid(x, y)

In [105]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [106]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [107]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]