# 난수 발생과 카운팅

In [1]:
import numpy as np  

### 시드 설정하기

In [3]:
np.random.rand(5)

array([0.73737511, 0.33719663, 0.47162491, 0.20433914, 0.13798723])

In [4]:
# 시드를 설정하고 랜덤을 돌렸을 때 다음에도 같은 숫자가 나옴.
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터의 순서바꾸기

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 무작위로 섞기 계속 바뀜
np.random.seed(2020)
np.random.shuffle(x)
x

array([4, 3, 7, 8, 1, 9, 5, 0, 2, 6])

### 데이터 샘플링

In [16]:
np.random.choice(5, 5, replace=False)

array([1, 2, 3, 4, 0])

In [17]:
np.random.choice(5, 3, replace=False)

array([4, 0, 2])

In [18]:
np.random.choice(5, 10)

array([3, 0, 4, 4, 0, 4, 1, 1, 2, 1])

In [19]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 2, 3, 2, 3, 3, 3, 3, 0, 3])

### 난수 생성

In [21]:
np.random.rand(5)

array([0.17779262, 0.84924802, 0.44237258, 0.83146771, 0.76392072])

In [24]:
np.random.randn(10)

array([ 0.40579787, -1.01923463, -1.34666654,  0.24346157,  0.48842328,
       -2.70572177,  0.65507847, -1.52570944, -0.71065857, -0.99861041])

In [28]:
np.random.randint(10, size=10)

array([6, 3, 2, 9, 5, 6, 6, 9, 3, 8])

In [29]:
np.random.randint(10, 20, size=10)

array([12, 17, 17, 10, 19, 18, 13, 14, 14, 16])

In [25]:
np.random.choice(2, 10)

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0])

In [26]:
x=np.random.choice(7, 100)
x.mean()

2.93

In [40]:
x = np.random.randn(250) * 100 + 10000
x[:10]

array([ 9738.83928261,  9934.82684154, 10172.26689866, 10005.73449625,
        9755.46969925, 10103.92352519, 10052.84578711,  9939.9942702 ,
       10041.62805107,  9989.78686478])

In [41]:
price = 10000
tomorrow = price *(1 + np.random.randn(1)/100.)
tomorrow

array([10196.55879807])

In [55]:
# 연습문제 3.5.2
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[-1]

11262.514488929331