### 백터와 백터의 곱셈

In [1]:
import numpy as np  

In [17]:
x = np.arange(1,4).reshape(3,1)
y = np.arange(4,7).reshape(3,1)
x,y

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [20]:
x.shape, y.shape

((3, 1), (3, 1))

In [22]:
x.T

array([[1, 2, 3]])

In [24]:
x.T @ y

array([[32]])

In [9]:
z.shape

(1, 1)

In [10]:
np.dot(x.T, y)

array([[32]])

In [25]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
y = x.T
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [31]:
z = np.zeros((len(x), len(y[0])), dtype = 'i')
for i in range(len(x)):
    for m in range(len(y[0])):
        val = 0
        for k in range(len(x[0])):
            val += x[i, k] * y[k,m]
        z[i,m] = val

z

array([[14, 32],
       [32, 77]], dtype=int32)

In [32]:
np.dot(x,y)

array([[14, 32],
       [32, 77]])

In [40]:
p = np.array([100, 80, 50])* 10000
n = np.array([3, 4, 5])

In [42]:
x = p @ n
x

8700000

In [45]:
A = np.array([1,2,3])
B = np.array([[4,7],[5,8],[6,9]])


array([[4, 7],
       [5, 8],
       [6, 9]])

In [46]:
A @ B

array([32, 50])

In [48]:
B.T @ A

array([32, 50])

In [50]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [51]:
A @ B

array([[19, 22],
       [43, 50]])

In [52]:
B @ A

array([[23, 34],
       [31, 46]])

In [53]:
A = np.array([[1,2],[3,4],[5,6]])

In [55]:
B = A.T

In [56]:
A @ B

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [57]:
B @ A

array([[35, 44],
       [44, 56]])

In [76]:
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [77]:
y = x.T

In [78]:
y

array([[1, 2, 3]])

In [79]:
# 정방행렬
x @ y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [80]:
# 스칼라
y @ x

array([[14]])