In [1]:
import numpy as np  

In [50]:
# 1번 길이가 10인 0- 벡터를 만드세요.
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
# 2번 길이가 10이면 다섯번째 원소만 1이고 나머지 원소는 모두 0 인 벡터를 만드세요.

b = np.eye(1,10, k=4)
b

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [64]:
# 3번 10부터 49까지의 값을 가지는 벡터를 만드세요
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [65]:
# 4번 위(3번) 벡터의 순서를 바꾸세요.
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [15]:
# 5번 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.
d = np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
# 6번 벡터 [1,2,0,0,4,0] 에서 원소 값이 0 이아닌 원소만 선택한 벡터를 만드세요
e = np.array([1,2,0,0,4,0])

e[e != 0]

array([1, 2, 4])

In [53]:
# 7번 3x3 단위 행렬을 만드세요

f = np.eye(N=3, M=3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# 8번 난수 원소를 가지는 3x3 행렬을 만드세요
g = np.random.rand(9).reshape(3,3)
g

array([[0.44678195, 0.40664797, 0.69142968],
       [0.40703984, 0.47080582, 0.51302945],
       [0.99231165, 0.57840087, 0.95060875]])

In [42]:
# 9번 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.
g.max(),g.min()

(0.9923116519602937, 0.4066479659702559)

In [43]:
# 10번 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.
g.mean(axis=1),g.mean(axis=0)

(array([0.5149532 , 0.46362504, 0.84044043]),
 array([0.61537782, 0.48528488, 0.71835596]))